-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2019-12-07 00:27:09 EET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE domenii (
    id_domeniu     NUMBER(4) NOT NULL,
    nume_domeniu   VARCHAR2(50) NOT NULL
);

ALTER TABLE domenii ADD CONSTRAINT domenii_pk PRIMARY KEY ( id_domeniu );

ALTER TABLE domenii ADD CONSTRAINT domenii_nume_domeniu_uk UNIQUE ( nume_domeniu );

CREATE TABLE firme (
    id_firma             NUMBER(4) NOT NULL,
    nume_firma           VARCHAR2(50) NOT NULL,
    numar_telefon        NUMBER(15) NOT NULL,
    email                VARCHAR2(70) NOT NULL,
    firme_nume_domeniu   VARCHAR2(50) NOT NULL,
    id_domeniu           NUMBER(4) NOT NULL
);

ALTER TABLE firme
    ADD CONSTRAINT firma_email_ck CHECK ( REGEXP_LIKE ( email,
                                                        '[a-z0-9._%-]+@[a-z0-9._%-]+\.[a-z]{2,4}' ) );

ALTER TABLE firme ADD CONSTRAINT firme_pk PRIMARY KEY ( id_firma );

ALTER TABLE firme ADD CONSTRAINT firme_nume_firma_uk UNIQUE ( nume_firma );

CREATE TABLE locatii (
    id_locatie     NUMBER(5) NOT NULL,
    judet          VARCHAR2(50) NOT NULL,
    nume_locatie   VARCHAR2(50) NOT NULL,
    adresa         VARCHAR2(120)
);

ALTER TABLE locatii ADD CONSTRAINT locatii_pk PRIMARY KEY ( id_locatie );

CREATE TABLE meserii (
    id_meserie           NUMBER(4) NOT NULL,
    nume_meserie         VARCHAR2(50) NOT NULL,
    tip_meserie          VARCHAR2(50) NOT NULL,
    salariu              NUMBER(5),
    nivel_studii         VARCHAR2(100),
    particularitati      VARCHAR2(100),
    meserii_nume_firma   VARCHAR2(50) NOT NULL,
    meserii_locatie      VARCHAR2(150) NOT NULL,
    id_firma             NUMBER(4) NOT NULL,
    id_locatie           NUMBER(5) NOT NULL
);

ALTER TABLE meserii ADD CONSTRAINT meserii_pk PRIMARY KEY ( id_meserie );

CREATE TABLE cos_meserii (
    id_meserie           NUMBER(4) NOT NULL,
    nume_meserie         VARCHAR2(50) NOT NULL,
    tip_meserie          VARCHAR2(50) NOT NULL,
    salariu              NUMBER(5),
    nivel_studii         VARCHAR2(100),
    particularitati      VARCHAR2(100),
    meserii_nume_firma   VARCHAR2(50) NOT NULL,
    meserii_locatie      VARCHAR2(150) NOT NULL,
    id_firma             NUMBER(4) NOT NULL,
    id_locatie           NUMBER(5) NOT NULL
);

ALTER TABLE firme
    ADD CONSTRAINT domenii_firme_fk FOREIGN KEY ( id_domeniu )
        REFERENCES domenii ( id_domeniu ) ON DELETE CASCADE;

ALTER TABLE meserii
    ADD CONSTRAINT firme_meserii_fk FOREIGN KEY ( id_firma )
        REFERENCES firme ( id_firma ) ON DELETE CASCADE;

ALTER TABLE meserii
    ADD CONSTRAINT locatii_meserii_fk FOREIGN KEY ( id_locatie )
        REFERENCES locatii ( id_locatie ) ON DELETE CASCADE;

CREATE SEQUENCE domenii_id_domeniu_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER domenii_id_domeniu_trg BEFORE
    INSERT ON domenii
    FOR EACH ROW
    WHEN ( new.id_domeniu IS NULL )
BEGIN
    :new.id_domeniu := domenii_id_domeniu_seq.nextval;
END;
/

CREATE SEQUENCE firme_id_firma_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER firme_id_firma_trg BEFORE
    INSERT ON firme
    FOR EACH ROW
    WHEN ( new.id_firma IS NULL )
BEGIN
    :new.id_firma := firme_id_firma_seq.nextval;
END;
/

CREATE SEQUENCE locatii_id_locatie_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER locatii_id_locatie_trg BEFORE
    INSERT ON locatii
    FOR EACH ROW
    WHEN ( new.id_locatie IS NULL )
BEGIN
    :new.id_locatie := locatii_id_locatie_seq.nextval;
END;
/

CREATE SEQUENCE meserii_id_meserie_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER meserii_id_meserie_trg BEFORE
    INSERT ON meserii
    FOR EACH ROW
    WHEN ( new.id_meserie IS NULL )
BEGIN
    :new.id_meserie := meserii_id_meserie_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                             10
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           4
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          4
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
